---
server:
  port: 8080

spring:
  rabbitmq:
    broker-url: tcp://127.0.0.1:15672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        output:
          destination: tasktopic