---
spring:
  application:
    name: Red Service
  datasource:
    url: jdbc:postgresql://localhost/task-demo-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org:
      springframework:
        cloud:
          task: DEBUG
